# Generated by Django 3.0.8 on 2020-07-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='stream',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil')], max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='year',
            field=models.IntegerField(choices=[(1, '1st year'), (2, '2nd year'), (3, '3rd year'), (4, '4th year')]),
        ),
    ]
