# Generated by Django 3.0.8 on 2020-07-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_app', '0002_auto_20200727_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='phone_no',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
