# Generated by Django 3.0.8 on 2020-07-29 19:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_app', '0006_auto_20200729_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 29, 19, 34, 27, 332036, tzinfo=utc)),
        ),
    ]
