# Generated by Django 3.0.8 on 2020-07-29 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_app', '0007_auto_20200730_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='date',
            field=models.DateField(default=datetime.date(2020, 7, 30)),
        ),
    ]
