# Generated by Django 3.0.8 on 2020-07-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_app', '0008_auto_20200730_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='year',
            field=models.CharField(choices=[('1st year', '1st year'), ('2nd year', '2nd year'), ('3rd year', '3rd year'), ('4th year', '4th year'), ('All years', 'All years')], max_length=10),
        ),
    ]
