# Generated by Django 3.0.8 on 2020-07-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_app', '0009_auto_20200730_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='stream',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil'), ('All Streams', 'All')], max_length=20),
        ),
    ]
